
#配置数据源的属性
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      useSSL=true   :安全连接  &serverTimezone=UTC  时区配置 ：mysql 5 不需要， mysql 8 没配置无法连接
      url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
      username: root
      password: hua133037
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #验证连接
      enable: true
   #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow: 
        deny: 
        url-pattern: /druid/*
  #thymeleaf的配置 
  thymeleaf: 
    cache: false
    enabled: true
#      web-stat-filter: 
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置mybatis-plus
mybatis-plus:
  mapper-locations:
   - classpath:mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: auto       #主键自增
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #mybatis-plus日志配置，方便在控制台查看sql语句执行
    
#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
  - /index.html*
  - /sys/toLogin*
  - /login/login*
  - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
  - /**
#修改服务器端口号
server:
  port: 8081